
import React from 'react';

interface LandingPageProps {
  onGetStarted: () => void;
  onLogin: () => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onGetStarted, onLogin }) => {
  return (
    <div className="min-h-screen bg-white text-slate-900 font-sans selection:bg-indigo-100 selection:text-indigo-700 overflow-x-hidden">
      {/* Navbar */}
      <nav className="max-w-7xl mx-auto px-6 py-6 flex justify-between items-center relative z-20">
        <div className="flex items-center gap-2">
            <div className="w-10 h-10 bg-indigo-600 rounded-lg flex items-center justify-center text-white text-xl shadow-lg shadow-indigo-200">
                <i className="fas fa-layer-group"></i>
            </div>
            <span className="text-xl font-extrabold tracking-tight hidden md:block">ExamFlow AI</span>
            <span className="text-xl font-extrabold tracking-tight md:hidden">ExamFlow</span>
        </div>
        <div className="flex gap-4">
            <button onClick={onLogin} className="text-slate-600 font-bold hover:text-indigo-600 transition-colors">
                Log In
            </button>
            <button onClick={onGetStarted} className="px-5 py-2.5 bg-indigo-600 text-white font-bold rounded-full hover:bg-indigo-700 transition-all shadow-lg hover:shadow-indigo-200">
                Get Started
            </button>
        </div>
      </nav>

      {/* Hero Section */}
      <header className="relative max-w-7xl mx-auto px-6 pt-6 pb-16 md:pt-20 md:pb-32 grid grid-cols-1 md:grid-cols-2 gap-12 items-center overflow-hidden md:overflow-visible">
        <div className="space-y-8 relative z-10 order-2 md:order-1">
            <div className="inline-block px-4 py-1.5 bg-amber-100 text-amber-800 text-xs font-bold uppercase tracking-wider rounded-full">
                For Nigerian Schools 🇳🇬
            </div>
            <h1 className="text-4xl md:text-6xl font-extrabold leading-tight text-slate-900">
                Create Perfect Exam Papers in <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-purple-600">Minutes.</span>
            </h1>
            <p className="text-lg md:text-xl text-slate-600 leading-relaxed max-w-lg">
                Stop typing questions for hours. Use AI to generate WAEC/NECO standard questions, or simply snap a photo of your handwritten notes.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 pt-4">
                <button onClick={onGetStarted} className="px-8 py-4 bg-indigo-600 text-white text-lg font-bold rounded-xl hover:bg-indigo-700 transition-all shadow-xl hover:shadow-indigo-300 flex items-center justify-center gap-2">
                    Start Creating Free <i className="fas fa-arrow-right"></i>
                </button>
                <button onClick={onLogin} className="px-8 py-4 bg-white text-slate-700 border-2 border-slate-200 text-lg font-bold rounded-xl hover:bg-slate-50 transition-all flex items-center justify-center gap-2">
                    <i className="fas fa-sign-in-alt"></i> School Login
                </button>
            </div>
            <p className="text-sm text-slate-400 flex items-center gap-2">
                <i className="fas fa-check-circle text-green-500"></i> No credit card required
                <span className="mx-2">•</span>
                <i className="fas fa-check-circle text-green-500"></i> Works on Phone & Laptop
            </p>
        </div>
        
        <div className="relative order-1 md:order-2">
            {/* Visual Abstract - Blobs constrained within header on mobile */}
            <div className="absolute top-10 right-10 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-blob"></div>
            <div className="absolute bottom-10 left-10 w-72 h-72 bg-indigo-300 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-blob animation-delay-2000"></div>
            
            <div className="relative bg-white rounded-2xl shadow-2xl border border-slate-100 p-4 md:p-6 transform rotate-2 hover:rotate-0 transition-transform duration-500 mx-auto max-w-sm md:max-w-none">
                <div className="flex items-center justify-between mb-6 border-b pb-4">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-indigo-100 rounded-full flex items-center justify-center text-indigo-600"><i className="fas fa-graduation-cap"></i></div>
                        <div>
                            <div className="font-bold text-lg">JSS 2 Basic Science</div>
                            <div className="text-xs text-slate-500">Generated by AI • 2 mins ago</div>
                        </div>
                    </div>
                    <span className="bg-green-100 text-green-700 text-xs font-bold px-2 py-1 rounded">READY</span>
                </div>
                <div className="space-y-4">
                    <div className="p-3 bg-slate-50 rounded-lg border border-slate-100">
                        <span className="text-xs font-bold text-slate-400">Question 1 (OBJ)</span>
                        <p className="font-medium text-slate-800 mt-1">Which of the following is a non-living thing?</p>
                        <div className="grid grid-cols-2 gap-2 mt-2">
                            <div className="text-xs bg-white p-2 rounded border text-slate-500">A. Goat</div>
                            <div className="text-xs bg-white p-2 rounded border text-slate-500">B. Tree</div>
                            <div className="text-xs bg-indigo-50 p-2 rounded border border-indigo-200 text-indigo-700 font-bold">C. Stone <i className="fas fa-check ml-1"></i></div>
                            <div className="text-xs bg-white p-2 rounded border text-slate-500">D. Bird</div>
                        </div>
                    </div>
                    <div className="p-3 bg-slate-50 rounded-lg border border-slate-100 opacity-60">
                         <span className="text-xs font-bold text-slate-400">Question 2 (Theory)</span>
                         <p className="font-medium text-slate-800 mt-1">Define the term 'Energy' and list 3 sources.</p>
                         <div className="h-2 bg-slate-200 rounded mt-2 w-full"></div>
                         <div className="h-2 bg-slate-200 rounded mt-1 w-2/3"></div>
                    </div>
                </div>
                <div className="mt-6 flex justify-between items-center">
                    <div className="flex -space-x-2">
                        <div className="w-8 h-8 rounded-full bg-blue-500 border-2 border-white"></div>
                        <div className="w-8 h-8 rounded-full bg-amber-500 border-2 border-white"></div>
                        <div className="w-8 h-8 rounded-full bg-slate-200 border-2 border-white flex items-center justify-center text-[10px] font-bold text-slate-600">+4</div>
                    </div>
                    <button className="bg-indigo-600 text-white text-xs font-bold px-4 py-2 rounded-lg shadow-lg">Download PDF</button>
                </div>
            </div>
        </div>
      </header>

      {/* Features Grid */}
      <section className="bg-slate-50 py-16 px-6">
        <div className="max-w-7xl mx-auto">
            <div className="text-center max-w-2xl mx-auto mb-12">
                <h2 className="text-3xl md:text-4xl font-extrabold text-slate-900 mb-4">Three Ways to Create</h2>
                <p className="text-slate-600">Whether you have handwritten notes, a topic in mind, or need past questions, we have you covered.</p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
                    <div className="w-14 h-14 bg-blue-100 rounded-xl flex items-center justify-center text-blue-600 text-2xl mb-6">
                        <i className="fas fa-camera"></i>
                    </div>
                    <h3 className="text-xl font-bold text-slate-900 mb-3">Snap-to-Text</h3>
                    <p className="text-slate-600 leading-relaxed">
                        Have handwritten questions? Just snap a photo. Our AI reads your handwriting and converts it into a typed exam paper instantly.
                    </p>
                </div>
                
                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 hover:shadow-xl hover:-translate-y-1 transition-all duration-300 relative overflow-hidden">
                    <div className="absolute top-0 right-0 bg-purple-600 text-white text-[10px] font-bold px-2 py-1 rounded-bl-lg">POPULAR</div>
                    <div className="w-14 h-14 bg-purple-100 rounded-xl flex items-center justify-center text-purple-600 text-2xl mb-6">
                        <i className="fas fa-magic"></i>
                    </div>
                    <h3 className="text-xl font-bold text-slate-900 mb-3">AI Generator</h3>
                    <p className="text-slate-600 leading-relaxed">
                        Select a Subject (e.g., Civic Education), a Topic, and Difficulty. The AI generates fresh, high-quality questions for you in seconds.
                    </p>
                </div>

                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
                    <div className="w-14 h-14 bg-emerald-100 rounded-xl flex items-center justify-center text-emerald-600 text-2xl mb-6">
                        <i className="fas fa-database"></i>
                    </div>
                    <h3 className="text-xl font-bold text-slate-900 mb-3">Question Bank</h3>
                    <p className="text-slate-600 leading-relaxed">
                        Access thousands of past questions. Search by topic or class and drag them directly into your exam paper.
                    </p>
                </div>
            </div>
        </div>
      </section>

      {/* Advanced Tools Section */}
      <section className="py-16 px-6">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center gap-16">
              <div className="flex-1">
                  <div className="inline-block px-3 py-1 bg-indigo-50 text-indigo-700 font-bold rounded-full text-xs mb-4">AI-POWERED TOOLS</div>
                  <h2 className="text-3xl md:text-4xl font-extrabold text-slate-900 mb-6">Smarter Exams, Better Results</h2>
                  <div className="space-y-6">
                      <div className="flex gap-4">
                          <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center text-amber-600 shrink-0"><i className="fas fa-brain"></i></div>
                          <div>
                              <h4 className="font-bold text-lg text-slate-900">Smart Options & Distractors</h4>
                              <p className="text-slate-600 text-sm">AI suggests "Smart Options" to replace weak wrong answers, making your multiple-choice questions harder to guess.</p>
                          </div>
                      </div>
                      <div className="flex gap-4">
                          <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center text-green-600 shrink-0"><i className="fas fa-list-check"></i></div>
                          <div>
                              <h4 className="font-bold text-lg text-slate-900">Instant Marking Guides</h4>
                              <p className="text-slate-600 text-sm">For theory questions, the AI automatically generates a detailed Marking Guide (Rubric) to help you grade consistently.</p>
                          </div>
                      </div>
                      <div className="flex gap-4">
                          <div className="w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center text-blue-600 shrink-0"><i className="fas fa-qrcode"></i></div>
                          <div>
                              <h4 className="font-bold text-lg text-slate-900">Secure QR Codes</h4>
                              <p className="text-slate-600 text-sm">Every paper gets a unique QR code. Scan it to access the digital version or verify the exam source instantly.</p>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="flex-1 w-full bg-slate-900 rounded-2xl p-6 md:p-8 shadow-2xl text-white relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500 rounded-full mix-blend-overlay filter blur-3xl opacity-20"></div>
                   <div className="relative z-10">
                       <div className="flex items-center justify-between mb-8">
                           <h3 className="font-bold"><i className="fas fa-robot mr-2"></i> AI Assistant</h3>
                       </div>
                       <div className="space-y-4">
                           <div className="bg-slate-800 p-4 rounded-lg rounded-tl-none border border-slate-700">
                               <p className="text-sm">I've noticed this question is a bit too easy for JSS 3.</p>
                           </div>
                           <div className="bg-indigo-600 p-4 rounded-lg rounded-tr-none self-end ml-12">
                               <p className="text-sm font-bold">Use "Fix Wrong Options" to make it harder.</p>
                           </div>
                            <div className="bg-slate-800 p-4 rounded-lg rounded-tl-none border border-slate-700">
                               <p className="text-sm">Done! I've replaced the obvious answers with plausible misconceptions.</p>
                           </div>
                       </div>
                       <div className="mt-8 pt-6 border-t border-slate-700 flex justify-between items-center">
                           <div className="text-xs text-slate-400">Compliance Check</div>
                           <div className="text-green-400 font-bold text-sm"><i className="fas fa-check-circle mr-1"></i> 100% Curriculum Compliant</div>
                       </div>
                   </div>
              </div>
          </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-300 py-12 px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
            <div className="flex items-center gap-2">
                <div className="w-8 h-8 bg-indigo-600 rounded flex items-center justify-center text-white">
                    <i className="fas fa-layer-group"></i>
                </div>
                <span className="text-lg font-bold text-white">ExamFlow AI</span>
            </div>
            <p className="text-sm text-center md:text-left">© {new Date().getFullYear()} ExamFlow AI. Built for Education.</p>
            <div className="flex gap-4">
                <a href="#" className="hover:text-white"><i className="fab fa-twitter"></i></a>
                <a href="#" className="hover:text-white"><i className="fab fa-facebook"></i></a>
                <a href="#" className="hover:text-white"><i className="fab fa-instagram"></i></a>
            </div>
        </div>
      </footer>
    </div>
  );
};
